platform :ios, '8.0'
use_frameworks!

def pods
pod "GPUImage”
pod "IQKeyboardManager"
pod "SnapKit"
pod "SDAutoLayout"
pod "SDWebImage"
pod "TYAlertController"
pod "SVProgressHUD"
pod "UITableView+FDTemplateLayoutCell"
pod "YYKit"
pod "MJExtension"
pod "FMDB"
pod "MJRefresh"
pod "pop"
pod "SwipeBack"

pod "PromiseKit", "~> 3.2"
pod 'AFNetworking', '~> 3.0'
pod 'BaiduMapKit'
pod 'ReactiveCocoa'
pod 'ObjectMapper'
pod 'FDFullscreenPopGesture'
end
target 'WelcomeNewHome' do
    pods
end
